// Code generated by protoc-gen-go. DO NOT EDIT.
// source: waterflow.proto

// protoc --go_out=plugins=grpc:. waterflow.proto

package waterflow

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type WaterFlowRequest struct {
	PageIndex            int32    `protobuf:"varint,1,opt,name=pageIndex,proto3" json:"pageIndex,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WaterFlowRequest) Reset()         { *m = WaterFlowRequest{} }
func (m *WaterFlowRequest) String() string { return proto.CompactTextString(m) }
func (*WaterFlowRequest) ProtoMessage()    {}
func (*WaterFlowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_c799e0f310a2d1ce, []int{0}
}

func (m *WaterFlowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaterFlowRequest.Unmarshal(m, b)
}
func (m *WaterFlowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaterFlowRequest.Marshal(b, m, deterministic)
}
func (m *WaterFlowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaterFlowRequest.Merge(m, src)
}
func (m *WaterFlowRequest) XXX_Size() int {
	return xxx_messageInfo_WaterFlowRequest.Size(m)
}
func (m *WaterFlowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_WaterFlowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_WaterFlowRequest proto.InternalMessageInfo

func (m *WaterFlowRequest) GetPageIndex() int32 {
	if m != nil {
		return m.PageIndex
	}
	return 0
}

func (m *WaterFlowRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type WaterFlowReply struct {
	// 错误详细信息
	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	// 操作状态
	// 0:操作成功
	// 1:操作失败
	Success bool `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	// 文章集合
	Data                 []*Article `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *WaterFlowReply) Reset()         { *m = WaterFlowReply{} }
func (m *WaterFlowReply) String() string { return proto.CompactTextString(m) }
func (*WaterFlowReply) ProtoMessage()    {}
func (*WaterFlowReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_c799e0f310a2d1ce, []int{1}
}

func (m *WaterFlowReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WaterFlowReply.Unmarshal(m, b)
}
func (m *WaterFlowReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WaterFlowReply.Marshal(b, m, deterministic)
}
func (m *WaterFlowReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WaterFlowReply.Merge(m, src)
}
func (m *WaterFlowReply) XXX_Size() int {
	return xxx_messageInfo_WaterFlowReply.Size(m)
}
func (m *WaterFlowReply) XXX_DiscardUnknown() {
	xxx_messageInfo_WaterFlowReply.DiscardUnknown(m)
}

var xxx_messageInfo_WaterFlowReply proto.InternalMessageInfo

func (m *WaterFlowReply) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *WaterFlowReply) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *WaterFlowReply) GetData() []*Article {
	if m != nil {
		return m.Data
	}
	return nil
}

type Article struct {
	ArticleId            string   `protobuf:"bytes,1,opt,name=articleId,proto3" json:"articleId,omitempty"`
	ArticleTitle         string   `protobuf:"bytes,2,opt,name=articleTitle,proto3" json:"articleTitle,omitempty"`
	LikeNum              int32    `protobuf:"varint,3,opt,name=likeNum,proto3" json:"likeNum,omitempty"`
	MoneyReward          float32  `protobuf:"fixed32,4,opt,name=moneyReward,proto3" json:"moneyReward,omitempty"`
	TotalReward          float32  `protobuf:"fixed32,5,opt,name=totalReward,proto3" json:"totalReward,omitempty"`
	ArticleCover         string   `protobuf:"bytes,6,opt,name=articleCover,proto3" json:"articleCover,omitempty"`
	CoverWH              float32  `protobuf:"fixed32,7,opt,name=coverWH,proto3" json:"coverWH,omitempty"`
	WhetherLike          bool     `protobuf:"varint,8,opt,name=whetherLike,proto3" json:"whetherLike,omitempty"`
	AuthorId             string   `protobuf:"bytes,9,opt,name=authorId,proto3" json:"authorId,omitempty"`
	AuthorIcon           string   `protobuf:"bytes,10,opt,name=authorIcon,proto3" json:"authorIcon,omitempty"`
	AuthorName           string   `protobuf:"bytes,11,opt,name=authorName,proto3" json:"authorName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Article) Reset()         { *m = Article{} }
func (m *Article) String() string { return proto.CompactTextString(m) }
func (*Article) ProtoMessage()    {}
func (*Article) Descriptor() ([]byte, []int) {
	return fileDescriptor_c799e0f310a2d1ce, []int{2}
}

func (m *Article) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Article.Unmarshal(m, b)
}
func (m *Article) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Article.Marshal(b, m, deterministic)
}
func (m *Article) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Article.Merge(m, src)
}
func (m *Article) XXX_Size() int {
	return xxx_messageInfo_Article.Size(m)
}
func (m *Article) XXX_DiscardUnknown() {
	xxx_messageInfo_Article.DiscardUnknown(m)
}

var xxx_messageInfo_Article proto.InternalMessageInfo

func (m *Article) GetArticleId() string {
	if m != nil {
		return m.ArticleId
	}
	return ""
}

func (m *Article) GetArticleTitle() string {
	if m != nil {
		return m.ArticleTitle
	}
	return ""
}

func (m *Article) GetLikeNum() int32 {
	if m != nil {
		return m.LikeNum
	}
	return 0
}

func (m *Article) GetMoneyReward() float32 {
	if m != nil {
		return m.MoneyReward
	}
	return 0
}

func (m *Article) GetTotalReward() float32 {
	if m != nil {
		return m.TotalReward
	}
	return 0
}

func (m *Article) GetArticleCover() string {
	if m != nil {
		return m.ArticleCover
	}
	return ""
}

func (m *Article) GetCoverWH() float32 {
	if m != nil {
		return m.CoverWH
	}
	return 0
}

func (m *Article) GetWhetherLike() bool {
	if m != nil {
		return m.WhetherLike
	}
	return false
}

func (m *Article) GetAuthorId() string {
	if m != nil {
		return m.AuthorId
	}
	return ""
}

func (m *Article) GetAuthorIcon() string {
	if m != nil {
		return m.AuthorIcon
	}
	return ""
}

func (m *Article) GetAuthorName() string {
	if m != nil {
		return m.AuthorName
	}
	return ""
}

func init() {
	proto.RegisterType((*WaterFlowRequest)(nil), "waterflow.WaterFlowRequest")
	proto.RegisterType((*WaterFlowReply)(nil), "waterflow.WaterFlowReply")
	proto.RegisterType((*Article)(nil), "waterflow.Article")
}

func init() { proto.RegisterFile("waterflow.proto", fileDescriptor_c799e0f310a2d1ce) }

var fileDescriptor_c799e0f310a2d1ce = []byte{
	// 353 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcd, 0x6e, 0xea, 0x30,
	0x10, 0x85, 0xc5, 0x3f, 0x19, 0xd0, 0xbd, 0x57, 0x5e, 0xf9, 0xd2, 0xaa, 0x8a, 0xb2, 0xa8, 0x58,
	0xb1, 0xa0, 0x4f, 0x50, 0x55, 0xa2, 0x45, 0x42, 0x2c, 0x4c, 0x25, 0xd6, 0x6e, 0x32, 0x85, 0x08,
	0x07, 0xa7, 0x8e, 0xd3, 0x94, 0xbe, 0x6f, 0xdf, 0xa3, 0xb2, 0xc9, 0x8f, 0xa9, 0xba, 0x9b, 0xf3,
	0x9d, 0xd1, 0xe1, 0x90, 0x31, 0xfc, 0x2d, 0xb8, 0x46, 0xf5, 0x2a, 0x64, 0x31, 0x4b, 0x95, 0xd4,
	0x92, 0x78, 0x35, 0x08, 0x56, 0xf0, 0x6f, 0x6b, 0xc4, 0x42, 0xc8, 0x82, 0xe1, 0x5b, 0x8e, 0x99,
	0x26, 0xd7, 0xe0, 0xa5, 0x7c, 0x87, 0xcb, 0x63, 0x84, 0x1f, 0xb4, 0xe5, 0xb7, 0xa6, 0x3d, 0xd6,
	0x00, 0x32, 0x81, 0xa1, 0x11, 0x9b, 0xf8, 0x13, 0x69, 0xdb, 0x9a, 0xb5, 0x0e, 0x04, 0xfc, 0x71,
	0xd2, 0x52, 0x71, 0x22, 0x14, 0x06, 0x09, 0x66, 0x19, 0xdf, 0xa1, 0x4d, 0xf2, 0x58, 0x25, 0x8d,
	0x93, 0xe5, 0x61, 0x88, 0x59, 0x66, 0x63, 0x86, 0xac, 0x92, 0xe4, 0x16, 0xba, 0x11, 0xd7, 0x9c,
	0x76, 0xfc, 0xce, 0x74, 0x34, 0x27, 0xb3, 0xa6, 0xfe, 0xbd, 0xd2, 0x71, 0x28, 0x90, 0x59, 0x3f,
	0xf8, 0x6a, 0xc3, 0xa0, 0x24, 0xa6, 0x33, 0x3f, 0x8f, 0xcb, 0xa8, 0xfc, 0xa5, 0x06, 0x90, 0x00,
	0xc6, 0xa5, 0x78, 0x8e, 0xb5, 0x38, 0xf7, 0xf6, 0xd8, 0x05, 0x33, 0x7d, 0x44, 0x7c, 0xc0, 0x75,
	0x9e, 0xd0, 0x8e, 0xfd, 0x5b, 0x95, 0x24, 0x3e, 0x8c, 0x12, 0x79, 0xc4, 0x13, 0xc3, 0x82, 0xab,
	0x88, 0x76, 0xfd, 0xd6, 0xb4, 0xcd, 0x5c, 0x64, 0x36, 0xb4, 0xd4, 0x5c, 0x94, 0x1b, 0xbd, 0xf3,
	0x86, 0x83, 0x9c, 0x06, 0x0f, 0xf2, 0x1d, 0x15, 0xed, 0x5f, 0x34, 0xb0, 0xcc, 0x34, 0x08, 0xcd,
	0xb0, 0x7d, 0xa2, 0x03, 0x9b, 0x50, 0x49, 0x93, 0x5f, 0xec, 0x51, 0xef, 0x51, 0xad, 0xe2, 0x03,
	0xd2, 0xa1, 0xfd, 0x5e, 0x2e, 0x32, 0x57, 0xe1, 0xb9, 0xde, 0x4b, 0xb5, 0x8c, 0xa8, 0x67, 0xb3,
	0x6b, 0x4d, 0x6e, 0x00, 0xca, 0x39, 0x94, 0x47, 0x0a, 0xd6, 0x75, 0x48, 0xe3, 0xaf, 0x79, 0x82,
	0x74, 0xe4, 0xfa, 0x86, 0xcc, 0x37, 0xe0, 0x6d, 0xab, 0x13, 0x90, 0x05, 0x8c, 0x1f, 0x51, 0xd7,
	0x57, 0x26, 0x57, 0xce, 0x79, 0x7e, 0xbe, 0xa4, 0xc9, 0xff, 0xdf, 0xcd, 0x54, 0x9c, 0x5e, 0xfa,
	0xf6, 0x29, 0xde, 0x7d, 0x07, 0x00, 0x00, 0xff, 0xff, 0xae, 0x73, 0x3a, 0x11, 0x9d, 0x02, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// WaterflowClient is the client API for Waterflow service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type WaterflowClient interface {
	GetWaterFlow(ctx context.Context, in *WaterFlowRequest, opts ...grpc.CallOption) (*WaterFlowReply, error)
}

type waterflowClient struct {
	cc *grpc.ClientConn
}

func NewWaterflowClient(cc *grpc.ClientConn) WaterflowClient {
	return &waterflowClient{cc}
}

func (c *waterflowClient) GetWaterFlow(ctx context.Context, in *WaterFlowRequest, opts ...grpc.CallOption) (*WaterFlowReply, error) {
	out := new(WaterFlowReply)
	err := c.cc.Invoke(ctx, "/waterflow.Waterflow/GetWaterFlow", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WaterflowServer is the server API for Waterflow service.
type WaterflowServer interface {
	GetWaterFlow(context.Context, *WaterFlowRequest) (*WaterFlowReply, error)
}

func RegisterWaterflowServer(s *grpc.Server, srv WaterflowServer) {
	s.RegisterService(&_Waterflow_serviceDesc, srv)
}

func _Waterflow_GetWaterFlow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WaterFlowRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WaterflowServer).GetWaterFlow(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/waterflow.Waterflow/GetWaterFlow",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WaterflowServer).GetWaterFlow(ctx, req.(*WaterFlowRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Waterflow_serviceDesc = grpc.ServiceDesc{
	ServiceName: "waterflow.Waterflow",
	HandlerType: (*WaterflowServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetWaterFlow",
			Handler:    _Waterflow_GetWaterFlow_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "waterflow.proto",
}
